# -*- coding: utf-8 -*-
"""Recursion assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oqZgY0bRorE2WIS7Ie8fpemOvPOOr0LF
"""

# ================================
#  RECURSION ASSIGNMENT
# ================================


# 1. Factorial of a Number
# Task: Find factorial using loop and recursion

# Using Loop
def factorial_loop(n):
    result = 1
    for i in range(1, n + 1):
        result *= i
    return result

# Using Recursion
def factorial_recursion(n):
    if n == 0 or n == 1:
        return 1
    return n * factorial_recursion(n - 1)


# 2. Sum of First N Natural Numbers
# Task: Calculate sum using loop and recursion

# Using Loop
def sum_loop(n):
    total = 0
    for i in range(1, n + 1):
        total += i
    return total

# Using Recursion
def sum_recursion(n):
    if n == 0:
        return 0
    return n + sum_recursion(n - 1)


# 3. Reverse a String
# Task: Reverse string using loop and recursion

# Using Loop
def reverse_loop(s):
    result = ""
    for char in s:
        result = char + result
    return result

# Using Recursion
def reverse_recursion(s):
    if len(s) == 0:
        return s
    return reverse_recursion(s[1:]) + s[0]


# 4. Fibonacci Sequence
# Task: Find first n Fibonacci numbers using loop and recursion

# Using Loop
def fibonacci_loop(n):
    fib = [0, 1]
    for i in range(2, n):
        fib.append(fib[i-1] + fib[i-2])
    return fib[:n]

# Using Recursion (single value)
def fibonacci_recursion(n):
    if n <= 1:
        return n
    return fibonacci_recursion(n-1) + fibonacci_recursion(n-2)

def fibonacci_list(n):
    return [fibonacci_recursion(i) for i in range(n)]


# 5. Sum of Digits of a Number
# Task: Find sum using while loop and recursion

# Using While Loop
def sum_digits_loop(n):
    total = 0
    while n > 0:
        total += n % 10
        n //= 10
    return total

# Using Recursion
def sum_digits_recursion(n):
    if n == 0:
        return 0
    return (n % 10) + sum_digits_recursion(n // 10)


# 6. Check Palindrome (String)
# Task: Check palindrome using loop and recursion

# Using Loop
def is_palindrome_loop(s):
    return s == s[::-1]

# Using Recursion
def is_palindrome_recursion(s):
    if len(s) <= 1:
        return True
    if s[0] != s[-1]:
        return False
    return is_palindrome_recursion(s[1:-1])


# 7. Maximum Element in a List
# Task: Find max using loop and recursion

# Using Loop
def max_loop(lst):
    maximum = lst[0]
    for num in lst:
        if num > maximum:
            maximum = num
    return maximum

# Using Recursion
def max_recursion(lst):
    if len(lst) == 1:
        return lst[0]
    return max(lst[0], max_recursion(lst[1:]))


# ================================
# LOGIC BUILDING QUESTIONS
# ================================


# 1. Factorial (again for practice)
# Already done above ✔️


# 2. Count Ways to Climb Stairs
# Task: You can take 1 or 2 steps

def climb_stairs(n):
    if n == 0 or n == 1:
        return 1
    return climb_stairs(n-1) + climb_stairs(n-2)


# ================================
# TESTING (Examples)
# ================================

print("Factorial (Loop):", factorial_loop(5))
print("Factorial (Recursion):", factorial_recursion(5))

print("Sum (Loop):", sum_loop(5))
print("Sum (Recursion):", sum_recursion(5))

print("Reverse (Loop):", reverse_loop("hello"))
print("Reverse (Recursion):", reverse_recursion("hello"))

print("Fibonacci (Loop):", fibonacci_loop(6))
print("Fibonacci (Recursion):", fibonacci_list(6))

print("Sum of Digits (Loop):", sum_digits_loop(1234))
print("Sum of Digits (Recursion):", sum_digits_recursion(1234))

print("Palindrome (Loop):", is_palindrome_loop("madam"))
print("Palindrome (Recursion):", is_palindrome_recursion("madam"))

print("Max (Loop):", max_loop([2, 5, 1, 9, 3]))
print("Max (Recursion):", max_recursion([2, 5, 1, 9, 3]))

print("Climb Stairs Ways:", climb_stairs(4))